workflows:
  version: 2.1
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Frontend install
          command: |
            npm run frontend:install
      - run:
          name: Backend install
          command: |
            npm run backend:install
      - run:
          name: Frontend build
          command: |
            CI=false npm run frontend:build
      - run:
          name: Backend build
          command: |
            CI=false npm run backend:build
      - run:
          name: Frontend deploy
          command: |
            npm run frontend:deploy
      - run:
          name: Backend deploy
          command: |
            npm run backend:deploy
      - run:
          name: Backend env secrets
          command: |
            npm run backend:env
